import Head from 'next/head'
import Searchbar from '../components/searchbar'
import { withAuth } from '../components/withAuth'

function Home() {
  return (
    <>
      <Head>
        <title>Mercury</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='flex w-full'>
        <div className='w-72 bg-zinc-700 text-white h-screen '>
          <Searchbar/>
          {/* displaying all chats */}
        </div>
        <div className='grow bg-zinc-600 h-screen text-zinc-100 '>
          {/* display selected chat */}
        </div>
      </div>
      
      
      
    </>
  )
}

export default withAuth(Home)
